env:
  browser: true
  es2021: true
extends:
  - standard
  - prettier
  - plugin:prettier/recommended
  - plugin:css/recommended
plugins:
  - html
  - css
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  comma-dangle:
    - error
    - never
  dot-notation: off
  quotes:
    - error
    - double
