[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build-wasm]
script = ["wasm-pack build"]

[tasks.build-www]
script = ["npm run build"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean", "build-wasm", "build-www"]

[tasks.serve-www]
script = ["npm run serve"]
dependencies = ["format", "build", "test"]

[tasks.dev]
script = ["npm run serve:dev"]
dependencies = ["build-wasm"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.my-flow]
dependencies = ["format", "build", "test"]
